USE `looqbox-challenge`;

SELECT 
    DEP_NAME,
    SECTION_NAME,
    SECTION_COD
FROM data_product
WHERE DEP_NAME IN ('BEBIDAS', 'PADARIA')
GROUP BY DEP_NAME, SECTION_NAME, SECTION_COD
ORDER BY DEP_NAME, SECTION_NAME;